CREATE TABLE `books` (
	`id` text PRIMARY KEY NOT NULL,
	`title` text NOT NULL,
	`stage` text DEFAULT 'Not started' NOT NULL,
	`progress` integer DEFAULT 0 NOT NULL,
	`is_active` integer DEFAULT false NOT NULL,
	`narrator_status` text DEFAULT 'Not designed' NOT NULL,
	`manuscript_ready` integer DEFAULT false NOT NULL,
	`voice_approved` integer DEFAULT false NOT NULL,
	`test_approved` integer DEFAULT false NOT NULL,
	`settings_locked` integer DEFAULT false NOT NULL,
	`rendering_complete` integer DEFAULT false NOT NULL,
	`qa_passed` integer DEFAULT false NOT NULL,
	`master_approved` integer DEFAULT false NOT NULL,
	`episodes_complete` integer DEFAULT 0 NOT NULL,
	`episodes_total` integer DEFAULT 0 NOT NULL,
	`corrections_open` integer DEFAULT 0 NOT NULL,
	`next_action` text DEFAULT 'Choose the next production step' NOT NULL,
	`target_date` text DEFAULT '' NOT NULL,
	`project_path` text DEFAULT '' NOT NULL,
	`notes` text DEFAULT '' NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
